config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  post '/', to: 'sessions#create'

  resources :articles do get "delete" , except: [:index] end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  delete 'logout', to:'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title,presence: true,length: {minimum:3,maximum: 50}
  validates :description,presence:true, length: {minimum:3,maximum:300}
  validates :user_id, presence: true

  def self.problem
    return 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :articles
  before_save { self.email = email.downcase}
   validates :username, presence: true,
   uniqueness: { case_sensitive: false },
   length: { minimum: 3, maximum: 25 }
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, length: { maximum: 105 },
   uniqueness: { case_sensitive: false },
   format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method:current_user,:logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged_in to perform that action"
      redirect_to root_path
    end
  end

 


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit,:update,:show,:destroy]
  before_action :require_same_user, only:[:edit,:update,:destroy,:show,]


  def new
    @article = Article.new
  end



  def create
    @article = Article.new(article_params)
    @article.user  = current_user

   if @article.save
      flash[:notice] = "Article was successfully created"
      #redirect_to article_path(@article)
    else
     render 'new'
    #render plain: params[:article].inspect
   # @article = Article.new(article_params)
  #  @article.save
   # redirect_to article_path(@article)
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
      @article = Article.all
      @article= Article.find(params[:id])
      @article.update_attributes(article_params)
    # if @article.update(article_params)
    #  flash[:notice] = "Article was successfully updated"
    #  @article = Article.all

      #redirect_to article_path(@article)
   # else
    #  render 'edit'
 #   end
  end

  def delete
    @article = Article.find(params[:article_id])

  end


  def destroy
    @user = @article.user
    @article.destroy
    flash[:notice] = "Article was successfully updated"
    #redirect_to user_path(@user)
  end



  private
   def article_params
     params.require(:article).permit(:title,:description)
   end



  private
   def set_article
     @article = Article.find(params[:id])
   end

  private
  def require_same_user
    if current_user != @article.user
      flash[:danger] = "You can only edit or delete you own articles"
      redirect_to root_path
    end



  end












end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
      if(logged_in?)
        user = User.find(session[:user_id])
      redirect_to user_path(user)
    
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully log in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was nothing wrong with your login information"
      render 'new'
    end


  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update,:show,:index]


  def index
    @users = User.paginate(page:params[:page],per_page:5)
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to users_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile Edited"
      redirect_to user_path(@user)

    else
      render 'edit'
    end
  end

  def show
   @user_articles = @user.articles.paginate(page: params[:page],per_page:5)
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
  def set_user
  @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
    flash[:danger] = "You can only edit your own account"
    redirect_to root_path
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size:100})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end

end

app/views/articles/_article.html.erb
<div class="well" style="min-height:75px">
  <%= link_to "New List Item", new_article_path, remote: true, class: "btn btn-primary" , :style => "float:right" %>
  </div>
  <div class="new-product"></div>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>

  </tr>
  </thead>

  <tbody class="product-index">
    <%= render 'articles/articleTable', obj: obj %>
  </tbody>


</table>

<div id="myModal" class="modal fade"></div>

app/views/articles/_articleTable.html.erb
<% obj.each do |article| %>

  <td><%= article.title %></td>
  <td><%= article.description %></td>
<td class="width-100"><%= link_to "Edit", edit_article_path(article), remote: true, class: "btn btn-default " %></td>
    <td><%= link_to "Delete", article_delete_path(article), remote: true, class: "btn btn-danger" %></td>

<% end %>

app/views/articles/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Product</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
    Are you sure you wish to delete <b><%= @article.title %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Product", article_path(@article), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/articles/_form.html.erb
    <div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @article, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        <div class="form-group">
          <%= f.label :title, class:"control-label" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, class: "control-label" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>
        
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_new.html.erb
<div class="modal-header">
<h3>New List Itemt</h3>
</div>
<%= render "form" %>

app/views/articles/_save.js.erb
  $(".product-index").html("<%= escape_javascript(render 'articleTable', obj: @current_user.articles.paginate(page: params[:page],per_page:5)) %>")
  $("#myModal").modal("hide")

app/views/articles/create.js.erb
<%= render "save" %>

app/views/articles/delete.js.erb
$("#myModal").html("<%= escape_javascript(render 'delete' ) %>")
$("#myModal").modal("show")

app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render 'form' %>

app/views/articles/error.html.erb
<h1> Page Not Found</h1>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p>
<%= link_to "Create new article", new_article_path %>
</p>

<%= render 'article' , obj:@articles %>
<%=will_paginate %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

<h2>Hellow</h2>

app/views/articles/new.js.erb
$("#myModal").html("<%= escape_javascript(render 'new') %>")
$("#myModal").modal("show")

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
   Title: <%= @article.title %>
</p>
<p>
  Description <%= @article.description %>
</p>
    <%= link_to 'Edit',edit_article_path(@article) %>

<%= link_to "Back to articles listing",articles_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to @current_user.username, user_path(@current_user.id) %></li>

            <li><%= link_to "Edit Profile", edit_user_path(@current_user.id) %></li>
            <li> <%= link_to 'Log out', logout_path,method: :delete %></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PageApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

   <%= javascript_include_tag   'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js'%>
    <%= stylesheet_link_tag  'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>

<style>

@import "bourbon";

body {
	background: #eee !important;
  padding-top:0px !important;
  margin-bottom:100px;
}

.wrapper {
	margin-top: 80px;
  margin-bottom: 80px;
}

.form-signin {
  max-width: 380px;
  padding: 15px 35px 45px;
  margin: 0 auto;
  background-color: #fff;
  border: 1px solid rgba(0,0,0,0.1);
}
  .form-signin-heading,
	.checkbox {
	  margin-bottom: 30px;
	}

	.checkbox {
	  font-weight: normal;
	}

	.form-control {
	  position: relative;
	  font-size: 16px;
	  height: auto;
	  padding: 10px;
		@include box-sizing(border-box);

		&:focus {
		  z-index: 2;
		}
	}

	input[type="text"] {
	  margin-bottom: -1px;
	  border-bottom-left-radius: 0;
	  border-bottom-right-radius: 0;
	}

	input[type="password"] {
	  margin-bottom: 20px;
	  border-top-left-radius: 0;
	  border-top-right-radius: 0;
	}

  .width-100{
    width:100px !important;
  }
}

  </style>
</head>
<body>
  <% if logged_in? %>
  <%= render 'layouts/navigation' %>
  <% end %>
  <%= render 'layouts/messages' %>
  <%= debug(params) if Rails.env.development? %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../stylesheets/starter-temlate.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home',root_path %></li>
            <li><%= link_to 'About',about_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1><%= link_to "Pages_App" , articles_path %></h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../assets/javascripts/bootstrap.min.js"></script>

  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../stylesheets/starter-temlate.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home',root_path %></li>
            <li><%= link_to 'About',about_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>This is Home Pages</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../assets/javascripts/bootstrap.min.js"></script>

  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevented the article from being created</h2>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
<% end %>


<div class="wrapper" style="margin-top: 80px; margin-bottom: 80px;">

  <%= form_for(@user,:html => {role: "form",class:"form-signin"}) do |f| %>
  <h2 class="form-signin-heading">
    <% if @user.new_record?  %>
      Sign up
    <% else %>
     Edit Profile
    <%end%>
  </h2>

  <%= f.text_field :username ,:class => "form-control" ,:placeholder => "User Name"%>

  <%= f.email_field :email ,:class => "form-control" ,:placeholder => "Email Address" %>

  <%= f.password_field :password ,:class => "form-control" , :placeholder => "Password"%>

  <%= f.submit @user.new_record? ? "Sign up" : "Update Account" , :class => "btn btn-lg btn-primary btn-block" %>
   <% if @user.new_record?  %>
      <%= link_to 'Login', root_path %>

    <%end%>

<% end %>
  </div>

app/views/users/edit.html.erb
<h1> Edit you User Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha Bloggers </h1>
<% @users.each do |user| %>
 <ul>
   <li><%= link_to gravatar_for(user),user_path(user) %></li>
   <li>
     <%= link_to user.username,user_path(user) %>
   </li>
   <li><small><%= pluralize(user.articles.count,"articles") if user.articles %></small></li>
</ul>
<% end %>
<%= will_paginate %>

app/views/users/new.html.erb
Create an account

<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <%= gravatar_for @user, size:150 ,:class=> "float-left"%>
<h2><%= @user.username %></h2>


<%=render 'articles/article', obj:@user_articles %>
<%= will_paginate @user_articles %>
</div>